[2021-01-21 05:11:09] Finnova.ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000] [1130] Host '122.170.231.1' is not allowed to connect to this MySQL server" at C:\xampp\htdocs\crm\application\Finnova\ORM\EntityManager.php line 159 {"exception":"[object] (PDOException(code: 1130): SQLSTATE[HY000] [1130] Host '122.170.231.1' is not allowed to connect to this MySQL server at C:\\xampp\\htdocs\\crm\\application\\Finnova\\ORM\\EntityManager.php:159)"} []
[2021-01-21 05:11:10] Finnova.ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000] [1130] Host '122.170.231.1' is not allowed to connect to this MySQL server" at C:\xampp\htdocs\crm\application\Finnova\ORM\EntityManager.php line 159 {"exception":"[object] (PDOException(code: 1130): SQLSTATE[HY000] [1130] Host '122.170.231.1' is not allowed to connect to this MySQL server at C:\\xampp\\htdocs\\crm\\application\\Finnova\\ORM\\EntityManager.php:159)"} []
